/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in to Iris' user
     * @description Issue a new session for Iris to access to the administrative endpoints.
     *     You need to create users in advance to log in.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve the information about currently logged in user. */
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get registered photos' list */
    get: operations["get_photos_list"];
    put?: never;
    /**
     * Registers a new photo
     * @description Upload a photo payload and register. This triggers the image processing.
     *     Note that the response from this endpoint does not guarantee (and practically does not mean)
     *     that the image has been generated. However representative_rgb is available, and the client can
     *     use this value to show the placeholder for the uploaded photo, until the image is being
     *     processed.
     *
     *     You need to be logged in to use this endpoint.
     */
    post: operations["new_photo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/by-hashes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get photos list by hashes list
     * @description Retrieves the list of photos from the list of hashes.
     *     You need to be logged in to use this endpoint.
     */
    post: operations["get_photos_list_by_hashes_list"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/sync/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * A new field
     * @description This is a new field. This initially returns implemented error.
     */
    post: operations["sync"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/{photo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a photo's meta */
    get: operations["get_photo_meta"];
    put?: never;
    post?: never;
    /**
     * A new field
     * @description This is a new field. This initially returns implemented error.
     */
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/{photo_id}/images": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Reprocess the photo
     * @description Reprocess the photos. This fills up the missing images.
     *     You need to be logged in to use this endpoint.
     */
    put: operations["reprocess"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/{photo_id}/images/{image_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get actual image
     * @description Retrieves the actual image binary payload.
     */
    get: operations["get_image"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Format: binary
     * @example <Binary Data>
     */
    BinaryBody: string;
    ClientError: {
      /** @example The value was invalid... */
      reason: string;
      /** @example error */
      status: string;
    };
    EntityName: string;
    GetPhotoMetaResponse: {
      photo: components["schemas"]["PhotoScheme"];
    };
    GetPhotosListByHashesListParam: {
      /**
       * @description Hashes to look up.
       * @example [
       *       "2653cb6500059d0316f40d0d24b7a11ace792a03eeab5b5e183275443e230612",
       *       "cb9e7fd9ead80d775c9cbe0fe5202a1f3202bcde6a9da92e54bc57a6e7b8931e"
       *     ]
       */
      hashes: string[];
    };
    GetPhotosListByHashesListResponse: {
      /**
       * @description The map of found hashes and corresponding photos.
       *     Note that this map does not necessarily include all hashes specified,
       *     as not found hashes will not be included.
       */
      photos: {
        [key: string]: components["schemas"]["PhotoReferenceSchema"];
      };
    };
    GetPhotosListResponse: {
      next_cursor?: null | components["schemas"]["Identifier"];
      photos: components["schemas"]["PhotoReferenceSchema"][];
      /** Format: int32 */
      total_count: number;
    };
    /** @example 202604-01ARZ3NDEKTSV4RRFFQ69G5FAV */
    Identifier: string;
    ImageMetaScheme: {
      /** @example jpg */
      ext: string;
      /**
       * Format: int32
       * @example 1080
       */
      height: number;
      /** @example image/jpeg */
      mime: string;
      /**
       * Format: int32
       * @example 1920
       */
      width: number;
    };
    LoginBody: {
      password: string;
      username: components["schemas"]["EntityName"];
    };
    LoginResponse: {
      session_key: string;
    };
    MeResponse: {
      name: components["schemas"]["EntityName"];
    };
    NewPhotoResponse: {
      photo: components["schemas"]["PhotoScheme"];
    };
    PhotoReferenceSchema: {
      federator?: null | components["schemas"]["EntityName"];
      id: components["schemas"]["Identifier"];
      images: {
        [key: string]: components["schemas"]["ImageMetaScheme"];
      };
      /** Format: int32 */
      month: number;
      original_sha256: string;
      representative_color: string;
      shot_time: string;
      tags: {
        [key: string]: string[];
      };
      /** Format: int32 */
      year: number;
    };
    PhotoScheme: {
      federator?: null | components["schemas"]["EntityName"];
      /** @description Identifier assigned to the created photo. */
      id: components["schemas"]["Identifier"];
      /**
       * @description The list of identifiers assigned to the specified images.
       *     The image ID is used to upload the actual image later.
       */
      images: {
        [key: string]: components["schemas"]["ImageMetaScheme"];
      };
      /**
       * @description The hexadecimal representation of SHA256 hash.
       * @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       */
      original_sha256: string;
      properties: components["schemas"]["PropertiesSchema"];
      /** @example #123456 */
      representative_color: string;
      shot_datetime: string;
      tags: {
        [key: string]: string[];
      };
    };
    PropertiesSchema: {
      /**
       * Format: double
       * @example 5.4
       */
      f_number?: number | null;
      /**
       * Format: double
       * @example 50
       */
      focal?: number | null;
      /**
       * @example [
       *       36.123456,
       *       138.123456
       *     ]
       */
      gps_lat_lng?: number[] | null;
      /**
       * Format: int64
       * @example 160
       */
      iso?: number | null;
      /** @example SIGMA */
      lens?: string | null;
      /** @example X-T4 */
      machine: string;
      /**
       * Format: float
       * @example 400
       */
      shutter_speed?: number | null;
      /** @example true */
      shutter_speed_controlled?: boolean | null;
    };
    /** @default null */
    ReprocessResponse: unknown;
    SuccessfulResponse_GetPhotoMetaResponse: {
      response: {
        photo: components["schemas"]["PhotoScheme"];
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_GetPhotosListByHashesListResponse: {
      response: {
        /**
         * @description The map of found hashes and corresponding photos.
         *     Note that this map does not necessarily include all hashes specified,
         *     as not found hashes will not be included.
         */
        photos: {
          [key: string]: components["schemas"]["PhotoReferenceSchema"];
        };
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_GetPhotosListResponse: {
      response: {
        next_cursor?: null | components["schemas"]["Identifier"];
        photos: components["schemas"]["PhotoReferenceSchema"][];
        /** Format: int32 */
        total_count: number;
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_LoginResponse: {
      response: {
        session_key: string;
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_MeResponse: {
      response: {
        name: components["schemas"]["EntityName"];
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_NewPhotoResponse: {
      response: {
        photo: components["schemas"]["PhotoScheme"];
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_ReprocessResponse: {
      /** @default null */
      response: unknown;
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_SyncResponse: {
      response: Record<string, never>;
      /** @example okay */
      status: string;
    };
    SyncResponse: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginBody"];
      };
    };
    responses: {
      /** @description The user has been successfully logged in and the session is issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_LoginResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
      /** @description The provided credential is not valid */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user has been successfully logged in and the session is issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_MeResponse"];
        };
      };
      /** @description The user is not logged in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_photos_list: {
    parameters: {
      query?: {
        /** @description The pagination cursor - retrieves from beginning */
        cursor?: string | null;
        /** @description the default is 50 */
        size?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The list of images. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetPhotosListResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  new_photo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": components["schemas"]["BinaryBody"];
      };
    };
    responses: {
      /** @description The photo was registered and the image processing was queued. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_NewPhotoResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
      /** @description There already was a photo registered with the matching hash */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_photos_list_by_hashes_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetPhotosListByHashesListParam"];
      };
    };
    responses: {
      /** @description Found photos. If no photo is found, the endpoint will return 200 OK with an empty array. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetPhotosListByHashesListResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  sync: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: components["schemas"]["EntityName"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo was successfully synchronized */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_SyncResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_photo_meta: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A found photo's metadata information. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetPhotoMetaResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo has been removed from the Iris */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
      /** @description The photo with the same ID is not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  reprocess: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo had unprocessed image(s) and was created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_ReprocessResponse"];
        };
      };
      /** @description All defined images were already creted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
        image_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo/image is found and the image payload is returned. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": components["schemas"]["BinaryBody"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
}
