name: Setup
inputs:
  pnpm-version:
    required: true
  node-version:
    required: true

runs:
  using: composite
  steps:
    - run: corepack enable; corepack prepare --activate
      shell: bash
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
