name: Setup
inputs:
  pnpm-version:
    required: true
  node-version:
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # 4.2.0
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
