/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the list of images. */
    get: operations["get_images_list"];
    put?: never;
    /**
     * Registers a new photo
     * @description Register a new photo, and prepare for the upload for the actual image.
     */
    post: operations["new_photo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/by-hashes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get photos list by hashes list
     * @description Retrieves the list of photos from the list of hashes.
     */
    post: operations["get_photos_list_by_hashes_list"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/{photo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a photo's meta
     * @description This is a new field. This initially returns implemented error.
     */
    get: operations["get_photo_meta"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/photos/{photo_id}/images/{image_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get actual image
     * @description Retrieves the actual image binary payload.
     */
    get: operations["get_image"];
    put?: never;
    /**
     * Registers a new photo
     * @description Register a new photo, and prepare for the upload for the actual image.
     */
    post: operations["upload_image"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Format: binary */
    BinaryBody: string;
    ClientError: {
      /** @example The value was invalid... */
      reason: string;
      /** @example error */
      status: string;
    };
    GetImagesListResponse: {
      next_cursor?: string | null;
      photos: components["schemas"]["PhotoReferenceSchema"][];
      /** Format: int32 */
      total_count: number;
    };
    GetPhotoMetaResponse: {
      photo: components["schemas"]["PhotoScheme"];
    };
    GetPhotosListByHashesListParam: {
      /**
       * @description Hashes to look up.
       * @example [
       *       "2653cb6500059d0316f40d0d24b7a11ace792a03eeab5b5e183275443e230612",
       *       "cb9e7fd9ead80d775c9cbe0fe5202a1f3202bcde6a9da92e54bc57a6e7b8931e"
       *     ]
       */
      hashes: string[];
    };
    GetPhotosListByHashesListResponse: {
      /**
       * @description The map of found hashes and corresponding photos.
       *     Note that this map does not necessarily include all hashes specified,
       *     as not found hashes will not be included.
       */
      photos: {
        [key: string]: components["schemas"]["PhotoReferenceSchema"];
      };
    };
    ImageReferenceSchema: {
      ext: string;
      /** Format: int32 */
      height: number;
      id: string;
    };
    NewImages: {
      /** @example jpg */
      ext: string;
      /**
       * Format: int32
       * @example 1080
       */
      height: number;
      /** @example 1080p */
      name: string;
      /**
       * Format: int32
       * @example 1920
       */
      width: number;
    };
    NewPhotoImageResponse: {
      /** @example 01AAAA */
      image_id: string;
      /** @example 1080p */
      name: string;
    };
    NewPhotoParam: {
      /**
       * @description The file name of the original picture.
       *     This is also used for the part of identification, but any arbitary string can be specified.
       * @example IMG_0001.JPG
       */
      file_name: string;
      /**
       * @description The hexadecimal representation of SHA256 hash.
       * @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       */
      original_sha256: string;
      properties: components["schemas"]["PropertiesSchema"];
      /**
       * @description The datetime the photo was taken.
       *     The shot timstamp is used for the part of identification and indexing.
       * @example 2026-01-02T03:45:06+09:00
       */
      shot_date: string;
      /**
       * @description The list of dimensions of the images to be uploaded later.
       *     Each images will get each image ID assigned for the later upload.
       */
      uploading_images: components["schemas"]["NewImages"][];
    };
    NewPhotoResponse: {
      /**
       * @description Identifier assigned to the created photo.
       * @example 202601_img_0001_jpg-01AAAA
       */
      id: string;
      /**
       * @description The list of identifiers assigned to the specified images.
       *     The image ID is used to upload the actual image later.
       */
      images: components["schemas"]["NewPhotoImageResponse"][];
      /**
       * Format: int32
       * @description How much of parallel upload is accepted for the upload of this image.
       */
      max_parallelism: number;
    };
    PhotoImages: {
      /** @example jpg */
      ext: string;
      /**
       * Format: int32
       * @example 1080
       */
      height: number;
      /** @example 01AAAA */
      image_id: string;
      /** @example 1080p */
      name: string;
      /**
       * Format: int32
       * @example 1920
       */
      width: number;
    };
    PhotoReferenceSchema: {
      id: string;
      images: components["schemas"]["ImageReferenceSchema"][];
      /** Format: int32 */
      month: number;
      original_sha256: string;
      shot_time: string;
      /** Format: int32 */
      year: number;
    };
    PhotoScheme: {
      /**
       * @description Identifier assigned to the created photo.
       * @example 202601_img_0001_jpg-01AAAA
       */
      id: string;
      /**
       * @description The list of identifiers assigned to the specified images.
       *     The image ID is used to upload the actual image later.
       */
      images: components["schemas"]["PhotoImages"][];
      /**
       * @description The hexadecimal representation of SHA256 hash.
       * @example e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
       */
      original_sha256: string;
      properties: components["schemas"]["PropertiesSchema"];
    };
    PropertiesSchema: {
      /**
       * Format: double
       * @example 5.4
       */
      f_number?: number | null;
      /**
       * Format: double
       * @example 50
       */
      focal?: number | null;
      /**
       * @example [
       *       36.123456,
       *       138.123456
       *     ]
       */
      gps_lat_lng?: number[] | null;
      /**
       * Format: int64
       * @example 160
       */
      iso?: number | null;
      /** @example SIGMA */
      lens?: string | null;
      /** @example X-T4 */
      machine: string;
      /**
       * Format: float
       * @example 400
       */
      shutter_speed?: number | null;
      /** @example true */
      shutter_speed_controlled?: boolean | null;
    };
    SuccessfulResponse_GetImagesListResponse: {
      response: {
        next_cursor?: string | null;
        photos: components["schemas"]["PhotoReferenceSchema"][];
        /** Format: int32 */
        total_count: number;
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_GetPhotoMetaResponse: {
      response: {
        photo: components["schemas"]["PhotoScheme"];
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_GetPhotosListByHashesListResponse: {
      response: {
        /**
         * @description The map of found hashes and corresponding photos.
         *     Note that this map does not necessarily include all hashes specified,
         *     as not found hashes will not be included.
         */
        photos: {
          [key: string]: components["schemas"]["PhotoReferenceSchema"];
        };
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_NewPhotoResponse: {
      response: {
        /**
         * @description Identifier assigned to the created photo.
         * @example 202601_img_0001_jpg-01AAAA
         */
        id: string;
        /**
         * @description The list of identifiers assigned to the specified images.
         *     The image ID is used to upload the actual image later.
         */
        images: components["schemas"]["NewPhotoImageResponse"][];
        /**
         * Format: int32
         * @description How much of parallel upload is accepted for the upload of this image.
         */
        max_parallelism: number;
      };
      /** @example okay */
      status: string;
    };
    SuccessfulResponse_UploadImageResponse: {
      response: {
        /**
         * @description Identifier assigned to the created photo.
         * @example 202601_img_0001_jpg-01AAAA
         */
        id: string;
        /**
         * Format: int32
         * @description How much of parallel upload is accepted for the upload of this image.
         */
        max_parallelism: number;
      };
      /** @example okay */
      status: string;
    };
    UploadImageResponse: {
      /**
       * @description Identifier assigned to the created photo.
       * @example 202601_img_0001_jpg-01AAAA
       */
      id: string;
      /**
       * Format: int32
       * @description How much of parallel upload is accepted for the upload of this image.
       */
      max_parallelism: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_images_list: {
    parameters: {
      query?: {
        /** @description The pagination cursor - retrieves from beginning */
        cursor?: string | null;
        /** @description the default is 50 */
        size?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo was registered and ready for image upload. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetImagesListResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  new_photo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewPhotoParam"];
      };
    };
    responses: {
      /** @description The photo was registered and ready for image upload. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_NewPhotoResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_photos_list_by_hashes_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GetPhotosListByHashesListParam"];
      };
    };
    responses: {
      /** @description The photo was registered and ready for image upload. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetPhotosListByHashesListResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_photo_meta: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo was registered and ready for image upload. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_GetPhotoMetaResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  get_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
        image_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The photo/image is found and the image payload is returned. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": components["schemas"]["BinaryBody"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
  upload_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        photo_id: string;
        image_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/octet-stream": components["schemas"]["BinaryBody"];
      };
    };
    responses: {
      /** @description The image was uploaded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessfulResponse_UploadImageResponse"];
        };
      };
      /** @description The parameter/body was invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClientError"];
        };
      };
    };
  };
}
